### ISSUE TITLE
Timings is undefined

### ISSUE THREAD

**Issue by petervdn** [kribblo/wav-audio-sprite#1]
When i run the example, the resulting `timings` variable is always undefined. The files are read, the resulting buffer does have a length, but i never seem to be able to get a timings-object.

**Comment by kribblo** [comment]
Weird, we've been using this code extensively for a long time daily at work, and looking at the code at the very worst you should at least get an empty object (`const timings = {};`) if something goes wrong inside the reader.

I think I need more details or some example that fails to have a chance of having a look at it.

**Comment by petervdn** [comment]
Hmm, do you maybe use a promise-lib that allows and handles multiple params in the resolve method? (I fixed it by resolving one object containing both buffer and the timings-json.)

**Comment by kribblo** [comment]
> do you maybe use a promise-lib that allows and handles multiple params in the resolve method

No, it's just plain node, but I think you're right according to spec.

Would be no problem to do something like `return resolve({encoded, timings});` instead. If you wish to PR I'll apply it, otherwise I'll try to get on it soonish.

**Comment by kribblo** [comment]
Please 0.1.3, updated docs and example as well.
